In [1]:
import numpy as np

In [44]:
a = 5

In [45]:
def test1 (x: np.ndarray):
    return np.sum((x-a)**2)

In [46]:
def test1_grad (x: np.ndarray):
    return (x-a)*2

In [47]:
X = np.array([1, 2, 4, 8])
(X-a)**2


array([16,  9,  1,  9])

In [81]:
def my_GD(
         x0: np.ndarray,
         T: int = 100,
         lr: float = 1e-3,
         use_grad: bool = True,
         use_crit: bool = False,
         crit: float = 1e-7,
         **kwargs) -> np.ndarray:
    if use_grad:
        df = kwargs['df']
    else:
        raise NotImplementedError()
    x = x0
    if use_crit:
        while (np.sum(np.absolute(df(x))) > crit):
            x -= lr*df(x)
    else:
        for _ in range(T):
            x -= lr*df(x)
    return x

In [82]:
xt = np.array([1., -2., 3.])

In [83]:
my_GD(x0 = xt, use_crit = True, df = test1_grad)

array([4.99999998, 4.99999997, 4.99999999])

In [71]:
np.sum(np.absolute(xt))

12.37954695458145

In [60]:
xt

array([4.99999999, 4.99999999, 5.        ])